# Generated by Django 3.0.3 on 2020-02-28 06:53

from django.db import migrations, models
import useractivity.models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(default='media/profileimage/user_default.jpg', upload_to=useractivity.models.user_directory_path),
        ),
    ]
