# Generated by Django 3.0.3 on 2020-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
