# Generated by Django 3.0.3 on 2020-03-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='complete',
            new_name='completed',
        ),
    ]
